### ISSUE TITLE
Ecobee: multiple databases?

### ISSUE THREAD

**Issue by jsquyres** [epiphany40223/epiphany#144]
As of today, the Ecobee SQLite3 database is 193MB.

On the one hand, we want all that data.  On the other hand, if it's already nearly 200MB after just a month or three, it's going to grow pretty big pretty quickly.

1. Does it matter that it's going to grow huge?
1. Should we take steps to make it not grow so huge?
    * E.g., should we have one SQLite database per month, or something?
    * And if we do that (e.g., split by month), will that make analyzing the data in the future more difficult?

@fowlerk Thoughts?

**Comment by fowlerk** [comment]
@jsquyres:  Keep in mind that the database contains runtime data for all thermostats back to the original in-service date (mid-July, 2019).  So, a bit longer than a couple of months for most of the data.  This is probably the bulk of the size, given this is data for 5-minute intervals, or just shy of 70K records for each thermostat for a month.  I calculate that to be about 500K records just for the runtime data since July.  The "snapshot" or hourly data has only been collected since around mid-October or so.  We probably can get a better indication of the growth-rate by observing the database size over the next few days/week or so.

In any case, yes, it will get pretty unwieldy.  If we can keep the file size under 500MB or so per dataset, I think it will be a bit more manageable for analysis.  I'm guessing that we may be able to stay around this size by breaking it up by year, but we should see that over the next few days or so.

I do think retaining all the data is probably a good idea, and disk space is cheap.  It's just a matter of deciding how much to keep in each dataset.

**Comment by jsquyres** [comment]
> @jsquyres: Keep in mind that the database contains runtime data for all thermostats back to the original in-service date (mid-July, 2019). So, a bit longer than a couple of months for most of the data. This is probably the bulk of the size, given this is data for 5-minute intervals, or just shy of 70K records for each thermostat for a month. 

Oh, very good point.

> I calculate that to be about 500K records just for the runtime data since July. The "snapshot" or hourly data has only been collected since around mid-October or so. We probably can get a better indication of the growth-rate by observing the database size over the next few days/week or so.

Cool.

> In any case, yes, it will get pretty unwieldy. If we can keep the file size under 500MB or so per dataset, I think it will be a bit more manageable for analysis. I'm guessing that we may be able to stay around this size by breaking it up by year, but we should see that over the next few days or so.

With hourly data, can you calculate what an average years' worth of data would be?  (i.e., maybe we should just break up the DB file by year)
 
> I do think retaining all the data is probably a good idea, and disk space is cheap. It's just a matter of deciding how much to keep in each dataset.

👍

**Comment by fowlerk** [comment]
@jsquyres:  So in making the latest mods to the application, I added a new API key specifically for debugging so that I didn't interfere with the production authorization tokens.  It's been running since yesterday evening locally, and I added some logic to calculate the DB growth each run.  Based on a small sample-set running since yesterday evening, I've been able to estimate that a full year's data would probably be on the order of magnitude of 1.2G in size.  This includes both the runtime (historical) as well as the snapshot (hourly) data.  A bit bigger than I'd hoped, but maybe still manageable if we break it up by year.

Here's a link to a Google sheet that I used for estimating if you're interested in taking a look:
(https://drive.google.com/open?id=1jlMtxNpWNXsyKVcsDrPJt88hcxBRZLYQPGyZGyFKBPg)

BTW, I have the changes we discussed complete and hope to get a new pull for the update(s) soon.
